########################################################################################
# <컨테이너목록>
# * 아래의 모든 컨테이너들을 일괄로 생성한다.
# 1. dstone-mysql(데이터베이스)
# 2. dstone-rabbitmq(RabbitMQ)
# 3. dstone-redis(Redis)
# 4. dstone-boot(프레임웍 Application )
# 5. dstone-batch(배치프레임웍 Application)
# 6. dstone-batch-server(배치프레임웍 Application 관리서버)
# 
# <사전작업>
# 1. 작업디렉토리 결정 후 템플릿 복사.
#   /workshop
#     └─ /dstone-mysql                             # <Database (MySQL)>
#        ├─ init-db/                               #   DB 초기화 스크립트
#        ├─ 01.dstone-mysql-docker.yml             #   개별 Docker Compose 빌드파일
#        └─ 02.dstone-mysql-docker-reg.sh          #   Docker Hub 등록 Shell
#     └─ /dstone-rabbitmq                          # <RabbitMQ>
#        ├─ init-data/                             #   초기 데이터
#        ├─ 01.dstone-rabbitmq-docker.yml          #   개별 Docker Compose 빌드파일
#        └─ 02.dstone-rabbitmq-docker-reg.sh       #   Docker Hub 등록 Shell
#     └─ /workshop/dstone-redis                    # <Redis>
#        ├─ 01.dstone-redis-docker.yml             #   개별 Docker Compose 빌드파일
#        └─ 02.dstone-redis-docker-reg.sh          #   Docker Hub 등록 Shell
#     └─ /dstone-boot                              # <Boot Application>
#        ├─ conf/                                  #   설정 파일
#        ├─ target/                                #   실행 파일
#        ├─ 01.dstone-boot-docker.yml              #   개별 Docker Compose 빌드파일
#        └─ 02.dstone-boot-docker-reg.sh           #   Docker Hub 등록 Shell
#     └─ /dstone-batch                             # <Batch Application>
#        ├─ conf/                                  #   설정 파일
#        ├─ target/                                #   실행 파일
#        ├─ 01.dstone-batch-docker.yml             #   개별 Docker Compose 빌드파일
#        └─ 02.dstone-batch-docker-reg.sh          #   Docker Hub 등록 Shell
#     └─ /dstone-batch-server                      # <Batch Admin Application>
#        ├─ conf/                                  #   설정 파일
#        ├─ target/                                #   실행 파일
#        ├─ 01.dstone-batch-server-docker.yml      #   개별 Docker Compose 빌드파일
#        └─ 02.dstone-batch-server-docker-reg.sh   #   Docker Hub 등록 Shell
#     └─ /workshop/dstone-boot-docker-compose.yml  # dstone-boot Docker Compose 빌드파일
#     └─ /workshop/dstone-batch-docker-compose.yml # dstone-batch Docker Compose 빌드파일
#     └─ /workshop/dstone-docker-compose.yml       # 전체 Docker Compose 빌드파일
# 
# <작업명령>
# 1. Docker Compose 실행
#   - docker-compose -p dstone -f /workshop/dstone-docker-compose.yml up -d
# 2. 로그 확인
#   - docker-compose -p dstone -f /workshop/dstone-docker-compose.yml logs -f
# 3. 중지 및 삭제
#   - docker-compose -p dstone -f /workshop/dstone-docker-compose.yml down -v
########################################################################################
services:
  
  # MySQL 데이터베이스 서버
  dstone-mysql:  
    # ---------- 최초작업일 때 ---------------------- #
    image: mysql:8.0
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-mysql:latest
    # --------------------------------------------- #    
    container_name: dstone-mysql
    environment:
      MYSQL_ROOT_PASSWORD: db2admin!@
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_0900_ai_ci
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dstone-mysql/init-db:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    networks:
      - dstone-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ 서버
  dstone-rabbitmq:    
    # ---------- 최초작업일 때 ---------------------- #
    image: rabbitmq:3.13-management
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-rabbitmq:latest
    # --------------------------------------------- #    
    container_name: dstone-rabbitmq
    hostname: dstone-rabbitmq
    ports:
      - "5672:5672"   # AMQP 프로토콜 포트
      - "15672:15672" # Management UI 포트
    environment:
      ###########################################################  
      # RABBITMQ_DEFAULT_USER/PASS/VHOST 와 RABBITMQ_LOAD_DEFINITIONS안에 
      # 동일한 사용자/브이호스트가 있으면 definitions 로딩이 스킵될 수 있음.
      # 따라서 RABBITMQ_LOAD_DEFINITIONS을 쓸 경우 RABBITMQ_DEFAULT_USER/PASS/VHOST 제거.
      ###########################################################  
      #RABBITMQ_DEFAULT_USER: jysn007
      #RABBITMQ_DEFAULT_PASS: db2admin!@
      #RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
      - ./dstone-rabbitmq/init-data/dstone-rabbitmq_data.json:/etc/rabbitmq/definitions.json:ro
      # 설정 파일 마운트
      - ./dstone-rabbitmq/init-data/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - dstone-network
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      
  # Redis 서버
  dstone-redis:    
    # ---------- 최초작업일 때 ---------------------- #
    image: redis:7.2
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-redis:latest
    # --------------------------------------------- #    
    container_name: dstone-redis
    hostname: dstone-redis
    ports:
      - "6379:6379"   # Redis 기본 포트
    ulimits:
      nofile:
        soft: 10032
        hard: 10032
    command: ["redis-server", "--protected-mode", "no"] 
    volumes:
      - redis_data:/data
    networks:
      - dstone-network
    restart: unless-stopped
      
  # Application 프레임웍 
  dstone-boot:
    # ---------- 최초작업일 때 ---------------------- #
    image: eclipse-temurin:21-jdk
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-boot:latest
    # --------------------------------------------- #    
    container_name: dstone-boot
    ports:
      - "7081:7081"
    volumes:
      - /workshop/dstone-boot/target/dstone-boot.war:/workshop/dstone-boot/target/dstone-boot.war
      - /workshop/dstone-boot/conf:/workshop/dstone-boot/conf
    networks:
      - dstone-network
    depends_on:
      - dstone-mysql
      - dstone-rabbitmq
      - dstone-redis
    command:
      - /bin/bash
      - -c
      - |
        echo "Starting Spring Boot Application..."
        java -Xms512m -Xmx1024m -Dspring.profiles.active=dev -jar /workshop/dstone-boot/target/dstone-boot.war net.dstone.DstoneBootApplication
    restart: unless-stopped
    #restart: "no"

  # 배치프레임웍 Application
  dstone-batch:    
    # ---------- 최초작업일 때 ---------------------- #
    image: eclipse-temurin:21-jdk
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-batch:latest
    # --------------------------------------------- #    
    container_name: dstone-batch
    ports:
      - "6081:6081"
    volumes:
      - /workshop/dstone-batch/target/dstone-batch-0.0.1-SNAPSHOT.jar:/workshop/dstone-batch/target/dstone-batch-0.0.1-SNAPSHOT.jar
      - /workshop/dstone-batch/conf:/workshop/dstone-batch/conf
    networks:
      - dstone-network
    depends_on:
      - dstone-mysql
    command:
      - /bin/bash
      - -c
      - |
        echo "Starting Spring Boot Application..."
        java -Xms512m -Xmx1024m -Dspring.profiles.active=dev -jar /workshop/dstone-batch/target/dstone-batch-0.0.1-SNAPSHOT.jar net.dstone.batch.common.DstoneBatchApplication
    restart: unless-stopped

  # 배치프레임웍 Application 관리서버
  dstone-batch-server:    
    # ---------- 최초작업일 때 ---------------------- #
    image: eclipse-temurin:21-jdk
    # --------------------------------------------- #    
    # ---------- Docker Hub 에서 가져올 때 ---------- #
    # image: jysn007/dstone-batch-server:latest
    # --------------------------------------------- #    
    container_name: dstone-batch-server
    env_file:
      - ./conf/env-dev.properties
    ports:
      - "9393:9393"
    volumes:
      # dstone-batch-server(배치관리프로그램)용 설정
      - /workshop/dstone-batch-server/target:/workshop/dstone-batch-server/target
      - /workshop/dstone-batch-server/conf:/workshop/dstone-batch-server/conf
      # dstone-batch(배치프로그램)용 설정
      - /workshop/dstone-batch/target:/workshop/dstone-batch/target
      - /workshop/dstone-batch/conf:/workshop/dstone-batch/conf
    networks:
      - dstone-network
    depends_on:
      - dstone-mysql
      - dstone-batch
    command:
      - /bin/bash
      - -c
      - |
        echo "Starting Dataflow Server..."
        java -Dspring.profiles.active=dev -jar /workshop/dstone-batch-server/target/spring-cloud-dataflow-server-2.11.5.jar --spring.config.location=/workshop/dstone-batch-server/conf/dataflow-server.yml
    restart: unless-stopped
    
networks:
  dstone-network:
    driver: bridge

volumes:
  # MySQL 볼륨
  mysql-data:
  # RabbitMQ 볼륨
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  # Redis 볼륨
  redis_data:
    driver: local